import { useEffect, useState } from "react";
import StatCard from "./StatCard"; 
import FilterButtons from "./FilterButtons";  
import SearchBar from "./SearchBar"; 
import Loader from "./Loader"; 
import "./Dashboard.css";

function Dashboard() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState("All");
  const [query, setQuery] = useState("");

  // Fetch Data
  const loadData = async () => {
    setLoading(true);
    
    
    // Mock data for demonstration purposes
    const mockData = {
      index: "Loading",
      trades: "Loading",
      turnover: "Loading",
      gainers: 0,
      losers: 0,
    };

    // Simulate network delay
    await new Promise(resolve => setTimeout(resolve, 1500));

    setData(mockData);
    setLoading(false);
  };

  // Auto-refresh every 30 sec
  useEffect(() => {
    loadData();
    const interval = setInterval(loadData, 30000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="dashboard-container">
      <div className="dashboard">
        <h1>Dashboard</h1>
        <p>
          Track NEPSE stocks with real-time AI-powered trading signals
          <span className="live-data-badge">LIVE DATA</span>
        </p>

        {/* STAT CARDS */}
        <div className="stats-grid">
          {/* NEPSE Index Card (Full Width) */}
          <StatCard title="NEPSE Index" value={data?.index} isLoading={loading} />

          {/* Small Cards (2x2 layout) */}
          <div className="small-stats-row">
            <StatCard title="Total Turnover" value={data?.turnover} isLoading={loading} />
            <StatCard title="Total Trades" value={data?.trades} isLoading={loading} />
          </div>
          <div className="small-stats-row">
            <StatCard title="Gainers" value={data?.gainers} isLoading={loading} />
            <StatCard title="Losers" value={data?.losers} isLoading={loading} />
          </div>
        </div>

        {/* SEARCH & FILTER */}
        <SearchBar setQuery={setQuery} />
        <FilterButtons selected={filter} setSelected={setFilter} />

        {/* LOADING SECTION */}
        {loading && <Loader />}
        
        {/* Footer/Disclaimer */}
        <div className="disclaimer">
          Data sourced from NEPSE via unofficial API. Signals generated by AI model for educational purposes only.
          <br />
          Auto-refreshing every 30 seconds
        </div>
      </div>
    </div>
  );
}

export default Dashboard;